[Ammo_Dummy]
ItemName="Leurre"

[DamTypeVehicleExplosion]
DeathString="%k a éliminé %o avec l'explosion d'un véhicule."
FemaleSuicide="%o était un peu trop proche du véhicule lors de l'explosion."
MaleSuicide="%o était un peu trop proche du véhicule lors de l'explosion."


[ROAmmoWeightMessage]
HeavyMessage="Le nouveau chargeur est lourd"
LightMessage="Le nouveau chargeur est léger"
VeryLightMessage="Le nouveau chargeur est très léger"

[ROArtilleryDamType]
DeathString="%o a été exterminé par un obus d'artillerie."
FemaleSuicide="%o a été emportée par son propre obus d'artillerie."
MaleSuicide="%o a été emporté par son propre obus d'artillerie."

[ROArtilleryMsg]
SavedPosition="Coordonnées d'artillerie enregistrées"
RequestStrike="Ici le chef de section, je demande une frappe d'artillerie"
StrikeDenied="Ici le QG, demande de frappe refusée"
StrikeConfirmed="Ici le QG, frappe d'artillerie confirmée"
NoCoords="Aucune coordonnée n'a été sélectionnée !"
InvalidTarget="Aucune cible valide pour l'artillerie !"
OutOfStrikes="Vous avez utlisé toutes les frappes d'artillerie disponibles pour cette mission"
TryAgainLater="Nous ne pouvons pas lancer de nouvelle frappe si vite !"
TryAgainSoon="Une nouvelle frappe d'artillerie sera bientôt disponible"
StrikesRemaining="Restant"
NoArtyAvailable="Recours à l'artillerie non disponible"

[RODaddyMessage]
DaddyMessage="Antarian est ton père !"

[RODeathMessage]
KilledString="tué(e) par"
SomeoneString="quelqu'un"

[RODemolitionChargePlacedMsg]
DemoChargePlaced="Charge de démolition en place, à couvert !"

[ROGameMessage]
NewTeamMessageRussian="a rejoint les forces Alliées."
NewTeamMessageGerman="a rejoint les forces de l'Axe."
FFKillMessage="a tué un coéquipier."
FFViolationMessage="Exclusion"
FFViolationMessageTrailer="due à une violation de la règle sur le tir allié."
FFDamageMessage="Vous avez blessé un coéquipier."
RoleChangeMsg="Vous tenterez de réapparaître en tant que "
MaxRoleMsg="Impossible de changer en "
LeftMessage=" a quitté le combat."
EnteredMessage=" a rejoint le combat."
NewPlayerMessage="Un nouveau soldat a rejoint le combat."

[ROGrenadeDamType]
DeathString="%o a été tué par la grenade de %k."
FemaleSuicide="%o a été tuée par sa propre grenade."
MaleSuicide="%o a été tué par sa propre grenade."

[ROHintManager]
Hints[0].Title="Bienvenue"
Hints[0].Hint="Bienvenue dans Red Orchestra !||Ces messages d'aide apparaîtront à différents moments du jeu. Lisez-les attentivement, votre survie en dépendra peut-être ! Vous pouvez néanmoins les désactiver à partir de l'onglet ATH du menu de configuration."
Hints[1].Title="Energie"
Hints[1].Hint="Votre énergie baisse lorsque vous courez ou vous sautez. Lorsque vous êtes à bout de souffle, vous ne pouvez plus courir ou sauter et vous devez vous arrêter un instant pour reprendre votre souffle."
Hints[2].Title=Sauter
Hints[2].Hint="Sauter dépense votre énergie. A utiliser avec modération !"
Hints[3].Title="Se pencher"
Hints[3].Hint="Appuyez sur %LeanRight% ou %LeanLeft% pour vous pencher. Cette fonction vous permet de jeter un coup d'œil derrière un mur sans trop vous exposer."
Hints[4].Title="Sélection d'unité"
Hints[4].Hint="Vous pouvez changer d'arme et d'unité à tout moment en appuyant sur la touche %SHOWMENU%. Les changements que vous choisissez seront pris en compte lors de votre prochaine réapparition."
Hints[5].Title="Visée"
Hints[5].Hint="Appuyez sur %ROIronSights% pour utiliser le viseur de votre canon. Cette vue augmente considérablement la précision de vos tirs."
Hints[6].Title="Précision"
Hints[6].Hint="Les armes automatiques offrent une meilleure précision lorsque vous tirez par courtes rafales."
Hints[7].Title="Positions"
Hints[7].Hint="Utilisez les touches numériques (%SWITCHWEAPON 1%, %SWITCHWEAPON 2%, %SWITCHWEAPON 3%, ...) pour changer de poste dans le véhicule."
Hints[8].Title="Membres d'équipage"
Hints[8].Hint="Un tank accueillant tout un équipage est bien plus efficace qu'un véhicule manié par un joueur seul. Essayez d'embarquer des coéquipiers en route vers l'objectif."
Hints[9].Title="Carte tactique"
Hints[9].Hint="Vous pouvez voir la carte des objectifs à prendre ou à défendre en appuyant sur %SHOWOBJECTIVES%."
Hints[10].Title="Points faibles"
Hints[10].Hint="Chaque tank a ses points faibles. Essayez de viser la fenêtre du conducteur ou l'interstice entre le châssis et la tourelle."
Hints[11].Title="Types de munitions"
Hints[11].Hint="Appuyez sur %SwitchFireMode% pour faire défiler les types de munitions disponibles pour votre tank."
Hints[12].Title="Recharger"
Hints[12].Hint="Utilisez la touche %ROManualReload% pour recharger votre arme. Un message "Chargeur lourd" vous prévient alors que le chargeur que vous venez d'armer est plus qu'à moitié plein."
Hints[13].Title="Grenades soviétiques"
Hints[13].Hint="Pour entamer la combustion de l'amorce d'une grenade soviétique, maintenez %FIRE% enfoncé, puis appuyez sur %ALTFIRE%. Relâchez la commande de tir pour lancer la grenade. Attention, si vous la gardez trop longtemps en main, elle risque de vous exploser à la figure !"
Hints[14].Title="Points de ralliement"
Hints[14].Hint="Lorsque vous utilisez la Visée avec les jumelles, utilisez %AltFire% pour définir un point de ralliement. Les points de ralliement apparaissent sur la carte tactique de tous vos coéquipiers."
Hints[15].Title="Coordonnées d'artillerie"
Hints[15].Hint="Lorsque vous utilisez la Visée avec les jumelles, utilisez %Fire% pour définir une cible pour l'artillerie. Une fois les coordonnées enregistrées, trouvez une radio et appuyez sur %USE% pour déclencher une frappe d'artillerie sur la cible."
Hints[16].Title="Recharger une mitrailleuse"
Hints[16].Hint="Les mitrailleuses ne peuvent être rechargées que si elles sont déployées."
Hints[17].Title="Réapprovisionnement"
Hints[17].Hint="Lorsque vous êtes à court de munitions pour votre mitrailleuse, vous pouvez utiliser les messages vocaux pour demander un réapprovisionnement. Les joueurs verront l'icone de réapprovisionnement apparaître sur la carte tactique. Appuyez sur %SpeechMenuToggle% pour ouvrir le menu des messages vocaux."
Hints[18].Title="Mitrailleuses déployées"
Hints[18].Hint="Les mitrailleurs ont généralement besoin d'être épaulés. Trouvez un coéquipier pour assurer vos arrières."
Hints[19].Title="Baïonnette"
Hints[19].Hint="De nombreuses armes peuvent être montées d'une baïllonnette. Appuyez sur %Deploy% pour fixer une baïonnette sur le canon de votre arme et sur %AltFire% pour frapper l'ennemi avec."
Hints[20].Title="Viser avec le Panzerfaust"
Hints[20].Hint="Vous pouvez changer la portée de votre Panzerfaust en appuyant sur la touche %Deploy%. Lorsque vous  visez, vous devez alors faire correspondre l'angle de tir avec la valeur sélectionnée."
Hints[21].Title="Grenades"
Hints[21].Hint="Les grenades ont un important rayon d'action. N'hésitez pas à plonger à couvert ou à courir !"
Hints[22].Title="Objectifs attaqués"
Hints[22].Hint="Les objectifs indiqués par un icone clignotant sont ceux subissant une attaque de l'ennemi. Que l'objectif soit attaqué ou défendu par l'ennemi, c'est à vous d'intervenir."
Hints[23].Title="Points de ralliement"
Hints[23].Hint="Les officiers peuvent définir des points de ralliement en cliquant sur la carte tactique. Ces points de ralliement apparaissent sur la carte tactique de tous leurs coéquipiers."
Hints[24].Title="Ordres & Requêtes"
Hints[24].Hint="Les officiers peuvent donner l'ordre d'attaquer ou de défendre des objectifs spécifiques. Ces objectifs apparaissent sur la carte sous différentes formes. De la même manière, les mitrailleuses nécessitant un réapprovisionnement apparaissent sur la carte tactique."
Hints[25].Title="Réapprovisionner une mitrailleuse"
Hints[25].Hint="Appuyez sur %ThrowMGAmmo% pour réapprovisionner un mitrailleur à court de munitions."
Hints[26].Title="Points"
Hints[26].Hint="Vous remportez 10 points lorsque vous participez à la capture d'un objectif."
Hints[27].Title="Capturer un objectif"
Hints[27].Hint="Pour capturer un objectif, vous devez d'abord parvenir jusqu'à lui. Une barre s'affiche alors dans votre ATH lorsque vous accédez à l'objectif. Vous aurez probablement besoin de plusieurs coéquipiers pour réussir."
Hints[28].Title="Précision"
Hints[28].Hint="Les positions accroupie et à plat ventre vous permettent de stabiliser votre arme et d'en atténuer le recul. Appuyez sur la touche %duck% pour vous accroupir, ou sur la touche %prone% pour vous mettre à plat ventre."
Hints[29].Title="Changer de canon"
Hints[29].Hint="Vous pouvez changer le canon de votre mitrailleuse en utilisant %ROMGOperation%. Notez que le canon du DP 28 n'est pas escamotable, alors attention à la surchauffe !"
Hints[30].Title="Officiers"
Hints[30].Hint="Lorsque vous prenez un objectif, la présence d'un officier vous gonfle le moral et vous facilite la tâche !"
Hints[31].Title="Plonger à terre"
Hints[31].Hint="Vous pouvez plonger à terre en appuyant sur %PRONE% lorsque vous courez, de manière à vous mettre rapidement à couvert. Vous pouvez utiliser cette tactique pour plonger par dessus un obstacle et vous mettre à couvert derrière lui."
Hints[32].Title="Attaquer une mitrailleuse"
Hints[32].Hint="Les mitrailleurs ont un champ de vision limité lorsque leur mitrailleuse est déployée. Attaquez-les par le côté ou l'arrière."
Hints[33].Title="Prendre appui"
Hints[33].Hint="Vous pouvez stabiliser votre arme en posant le canon sur n'importe quelle surface horizontale ou verticale. Un icone apparaîtra alors en bas à droite de l'écran pour indiquer que vous pouvez prendre appui."
Hints[34].Title="Points de vue"
Hints[34].Hint="Utilisez les touches %PREVWEAPON% et %NEXTWEAPON% pour faire défiler les différentes vues disponibles pour chaque poste dans le véhicule. Soyez prudent lorsque vous passez la tête hors de la trappe, vous devenez alors beaucoup plus vulnérable."
Hints[35].Title="Conduire un tank"
Hints[35].Hint="Utilisez les touches de déplacement pour diriger votre tank. Utilisez la touche %JUMP% pour freiner."
Hints[36].Title="Utiliser le blindage"
Hints[36].Hint="Lorsque vous combattez d'autres tanks, n'oubliez pas que le blindage est plus épais à l'avant. Essayez de présenter le blindage légèrement de biais pour éviter les impacts directs."
Hints[37].Title="Portée du canon"
Hints[37].Hint="Utilisez les touches %LEANLEFT% et %LEANRIGHT% pour ajuster la portée du canon de votre tank. La portée sélectionnée est affichée en mètres en bas à droite de l'écran."
Hints[38].Title="Mitrailleuse coaxiale"
Hints[38].Hint="La plupart des tanks disposent d'une mitrailleuse coaxiale montée à côté du canon principal. Vous pouvez l'actionner depuis le poste de commandant en appuyant sur %ALTFIRE%. Remarque : le réglage de la portée n'a pas d'effet sur la mitrailleuse."
Hints[39].Title="Charges explosives"
Hints[39].Hint="Les charges explosives sont utiles pour détruire les véhicules ennemis et certains objectifs. Toutes les cartes ne présentent pas d'objectifs destructibles, mais lorsque c'est le cas, ces objectifs sont spécifiés sur la carte tactique."
Hints[40].Title="Grenades allemandes"
Hints[40].Hint="L'amorce des grenades allemandes se consume dès que vous appuyez sur %FIRE% ou %ALTFIRE%."
Hints[41].Title="Déployer une mitrailleuse"
Hints[41].Hint="Pour optimiser l'utilisation d'une mitrailleuse, vous devez la déployer. Pour ce faire, mettez-vous à plat ventre sur une surface plane. L'icone de déploiement apparaîtra en bas à droite de l'ATH. Appuyez sur %Deploy% pour déployer votre arme."
Hints[42].Title="Corps à corps"
Hints[42].Hint="Vous pouvez frapper un ennemi avec la crosse de votre arme en appuyant sur %ALTFIRE%. Plus vous maintenez cette commande enfoncée, plus le coup sera puissant. Visez la tête pour tuer votre ennemi d'un seul coup !"
Hints[43].Title="Armer un fusil"
Hints[43].Hint="Lorsque vous utilisez un fusil à culasse mobile, vous devez l'armer manuellement. Après avoir tiré, appuyez de nouveau sur %FIRE% pour armer votre fusil. Double-cliquez rapidement pour tirer et préparer le tir suivant dans la foulée."
Hints[44].Title="Messages cruciaux"
Hints[44].Hint="Les messages cruciaux sont affichés en haut à gauche de l'écran. Lisez-les attentivement pour rester informé de la situation."

[ROHud]
ReinforcementText="Renforts : "
TimeRemainingText="Temps restant : "
ViewingText="Vue : "
NoReinforcementsText="Aucun renfort disponible"
TeamMessagePrefix="*SECTION* "
ObjectivesText="OBJECTIFS"
PlayersNeededText="Requiert : "
SpectateInstructionText1="Appuyez sur Tir pour suivre un autre joueur"
SpectateInstructionText2="Appuyez sur Tir secondaire pour changer de mode Spectateur"
SpectateInstructionText3="Appuyez sur Visée pour basculer de la vue subjective à la vue à la troisième personne"
SpectateInstructionText4="Appuyez sur Saut pour revenir à la vue Personnage"
NeedAmmoText="Requiert munitions"
CanResupplyText="Appuyez sur %THROWMGAMMO% pour réapprovisionner"
OpenMapText="%SHOWOBJECTIVES% pour ouvrir"
SituationMapInstructionsText="Appuyez sur %SHOWOBJECTIVES% pour ouvrir ou fermer la carte tactique"
MapCoordTextX[0]="1"
MapCoordTextX[1]="2"
MapCoordTextX[2]="3"
MapCoordTextX[3]="4"
MapCoordTextX[4]="5"
MapCoordTextX[5]="6"
MapCoordTextX[6]="7"
MapCoordTextX[7]="8"
MapCoordTextX[8]="9"
MapCoordTextY[0]="A"
MapCoordTextY[1]="B"
MapCoordTextY[2]="C"
MapCoordTextY[3]="D"
MapCoordTextY[4]="E"
MapCoordTextY[5]="F"
MapCoordTextY[6]="G"
MapCoordTextY[7]="H"
MapCoordTextY[8]="I"
LegendAxisObjectiveText="Obj. tenu par Axe"
LegendAlliesObjectiveText="Obj. tenu par Alliés"
LegendNeutralObjectiveText="Objectif neutre"
LegendArtilleryRadioText="Radio artillerie"
LegendResupplyAreaText="Réapprovisionnement"
LegendRallyPointText="Point de ralliement"
LegendSavedArtilleryText="Coordonnées enreg."
LegendOrderTargetText="Cible désignée"
LegendArtyStrikeText="Frappe d'artillerie"
LegendHelpRequestText="Requiert aide sur obj."
LegendDestroyableItemText="Cible destructible"
LegendDestroyedItemText="Cible détruite"
LegendMGResupplyText="MG requiert munitions"
LegendVehResupplyAreaText="Réapp. véhicules"
LegendATGunText="Canon antichar"
SmallFontArrayNames[0]="ROFontsTwo.ROArial24DS"
SmallFontArrayNames[1]="ROFontsTwo.ROArial24DS"
SmallFontArrayNames[2]="ROFontsTwo.ROArial22DS"
SmallFontArrayNames[3]="ROFontsTwo.ROArial22DS"
SmallFontArrayNames[4]="ROFontsTwo.ROArial18DS"
SmallFontArrayNames[5]="ROFontsTwo.ROArial14DS"
SmallFontArrayNames[6]="ROFontsTwo.ROArial12DS"
SmallFontArrayNames[7]="ROFontsTwo.ROArial9DS"
SmallFontArrayNames[8]="ROFontsTwo.ROArial7DS"
MenuFontArrayNames[0]="ROFonts.ROBtsrmVr18"
MenuFontArrayNames[1]="ROFonts.ROBtsrmVr14"
MenuFontArrayNames[2]="ROFonts.ROBtsrmVr12"
MenuFontArrayNames[3]="ROFonts.ROBtsrmVr9"
MenuFontArrayNames[4]="ROFonts.ROBtsrmVr7"
CriticalMsgFontArrayNames[0]="ROFonts.ROArial28"
CriticalMsgFontArrayNames[1]="ROFonts.ROArial26"
CriticalMsgFontArrayNames[2]="ROFonts.ROArial24"
CriticalMsgFontArrayNames[3]="ROFonts.ROArial22"
CriticalMsgFontArrayNames[4]="ROFonts.ROArial18"
CriticalMsgFontArrayNames[5]="ROFonts.ROArial16"
CriticalMsgFontArrayNames[6]="ROFonts.ROArial14"
CriticalMsgFontArrayNames[7]="ROFonts.ROArial12"
CriticalMsgFontArrayNames[8]="ROFonts.ROArial9"
MapTimerTitle.Text="Temps restant"
MapLegendTitle.Text="Légende"
MapObjectivesTitle.Text="Objectifs"
MapRequiredObjectivesTitle.Text="Objectifs principaux"
MapSecondaryObjectivesTitle.Text="Objectifs secondaires"
FontArrayNames[0]="ROFonts.ROBtsrmVr28"
FontArrayNames[1]="ROFonts.ROBtsrmVr26"
FontArrayNames[5]="ROFonts.ROBtsrmVr16"
FontArrayNames[6]="ROFonts.ROBtsrmVr14"
FontArrayNames[7]="ROFonts.ROBtsrmVr12"
FontArrayNames[8]="ROFonts.ROBtsrmVr9"

[ROLastObjectiveMsg]
AboutToWin="Dernier objectif -- nous avons presque gagné la bataillle !"
AboutToLose="Dernier objectif -- nous avons presque perdu la bataillle !"

[ROLevelInfo]
Axis.UnitName="Axe"
Allies.UnitName="Alliés"
AxisUnitDescription="Description d'unité des forces de l'Axe pour cette carte."
AlliesUnitDescription="Description d'unité des forces Alliées pour cette carte."

[ROMineDamType]
DeathString="%o a sauté sur une mine."
FemaleSuicide="%o a sauté sur une mine."
MaleSuicide="%o a sauté sur une mine."

[ROMineVolume]
WarningMessage="Attention : vous êtes entré sur un champ de mines !!!"

[ROObjective]
objName="Sans nom"

[ROObjectiveMsg]
AxisCapture="Les forces de l'Axe ont capturé "
AlliesCapture="Les forces Alliées ont capturé "
AxisTriggeredMessage="Les forces de l'Axe ont détruit "
AlliesTriggeredMessage="Les forces Alliées ont détruit "

[ROPlayer]
SpectatingModeName[0]="Personnage"
SpectatingModeName[1]="Vue libre"
SpectatingModeName[2]="Joueurs"
SpectatingModeName[3]="Points de vue"

[RORallyMsg]
SavedPosition="Point de ralliement sauvegardé"
CheckObjectives="Nouveau point de ralliement - Consultez votre carte !"
RallySpam="Impossible de changer de point de ralliement si vite !"

[ROReinforcementMsg]
LowReinforcements="Nous avons besoin de renforts !"
NoReinforcements="Aucun renfort disponible !"

[ROResupplyMessage]
ResuppliedGunner="Approvisionnement réussi de "
BeenResupplied="Vous avez reçu des munitions de "

[RORoleInfo]
InfoText="Aucune information fournie."

[RORoundOverMsg]
AxisWins="Les forces de L'Axe remportent la bataille !"
AlliesWins="Les forces Alliées remportent la bataille !"
NoDecisiveOutcome="Les deux camps n'ont pas pu se départager"

[ROSatchelDamType]
DeathString="%o a été tué par la charge explosive de %k."
FemaleSuicide="%o a été tuée par sa propre charge explosive."
MaleSuicide="%o a été tué par sa propre charge explosive."

[ROSayDeadMessage]
MessagePrefix="(MORT) "
SpecPrefix="(SPECTATEUR) "

[ROSuicided]
DeathString="%o s'est tué."
FemaleSuicide="%o s'est tué."

[ROTankCannon]
ProjectileDescriptions=("AP","HE")

[ROTankShellExplosionDamage]
DeathString="%o a été tué par un éclat d'obus de tank de %k."
FemaleSuicide="%o a tiré son obus trop vite."
MaleSuicide="%o a tiré son obus trop vite."

[ROTeamGame]
ROHints=("Vous pouvez voir la carte des objectifs à prendre ou à défendre en appuyant sur %SHOWOBJECTIVES%.","Pour entamer la combustion de l'amorce d'une grenade soviétique F-1, maintenez la commande de tir enfoncée.", "Pour capturer un objectif, vous devez d'abord parvenir jusqu'à lui. Vous aurez probablement besoin de plusieurs coéquipiers pour réussir.","Appuyez sur %PLAYERMENU 2% pour changer d'unité en cours de partie et sur, %PLAYERMENU% pour changer de camp.","Pour passer en mode Visée et améliorer ainsi la précision de vos tirs, appuyez sur %ROIRONSIGHTS%.", "Vous remportez 10 points lorsque vous participez à la capture d'un objectif.", "Les positions accroupie et à plat ventre vous permettent de stabiliser votre arme et d'en atténuer le recul. ","Pour régénérer votre énergie, arrêtez-vous et reposez-vous un moment.","Vous pouvez déployer une mitrailleuse sur presque n'importe quelle surface. Appuyez sur %DEPLOY% quand l'icone de déploiement s'affiche.","Lorsque vous rechargez, un message "Chargeur lourd" vous prévient que le chargeur que vous venez d'armer est plus qu'à moitié plein.", "Les mitrailleuses ne peuvent être rechargées que si elles sont déployées.","Les joueurs reçoivent 1 point lorsqu'ils approvisionnent un mitrailleur à court de munitions.", "Les mitrailleuses offrent une meilleure précision lorsque vous tirez par courtes rafales.","Le canon du DP 28 n'est pas escamotable, alors attention à la surchauffe !", "Lorsque vous prenez un objectif, la présence d'un officier vous gonfle le moral et vous facilite la tâche !", "Les mitrailleurs ont généralement besoin d'être épaulés. Trouvez un coéquipier pour assurer vos arrières.", "Les mitrailleurs ont un champ de vision limité lorsque leur mitrailleuse est déployée. Attaquez-les par le côté ou l'arrière.")
PropsDisplayText[0]="Niveau IA"
PropsDisplayText[1]="Utiliser rotation cartes"
PropsDisplayText[2]="Vitesse de jeu"
PropsDisplayText[3]="Spectateurs maximum"
PropsDisplayText[4]="Joueurs maximum"
PropsDisplayText[5]="Limite de temps "
PropsDisplayText[6]="Autoriser vue externe"
PropsDisplayText[7]="Vue subjective mode Spectateur"
PropsDisplayText[8]="Vue 3e personne mode Spectateur"
PropsDisplayText[9]="Autoriser points de vue spectateurs"
PropsDisplayText[10]="Autoriser vue libre spectateurs"
PropsDisplayText[11]="Autoriser vue libre mort"
PropsDisplayText[12]="Autoriser pause admin"
PropsDisplayText[13]="Joueurs minimum"
PropsDisplayText[14]="Mode bots"
PropsDisplayText[15]="Délai en fin de partie"
PropsDisplayText[16]="Ajuster IA"
PropsDisplayText[17]="Limite de score"
PropsDisplayText[18]="Limite de manches"
PropsDisplayText[19]="Temps avant lancement"
PropsDisplayText[20]="Attente réseau"
PropsDisplayText[21]="Joueurs minimum"
PropsDisplayText[22]="Les joueurs doivent être prêts"
PropsDisplayText[23]="Echelle tir allié"
PropsDisplayText[24]="Echelle artillerie tir allié"
PropsDisplayText[25]="Echelle explosifs tir allié"
PropsDisplayText[26]="Bots équilibrent équipes"
PropsDisplayText[27]="Equilibrage des équipes"
PropsDisplayText[28]="Discussion privée entre équipes"
PropsDisplayText[29]="Temps d'éjection des traînards"
PropsDisplayText[30]="Pénalité tir ami"
PropsDisplayText[31]="Mode message mort"
PropsDisplayText[32]="Ecran noir quand mort"
PropsDisplayText[33]="Ecran noir en vues non-joueur"
PropDescText[0]="Définir le niveau de compétences des adversaires IA."
PropDescText[1]="La carte changera automatiquement si un match se termine ou si le temps est écoulé."
PropDescText[2]="Définir la vitesse du temps de jeu."
PropDescText[3]="Définir le nombre maximum de spectateurs de la partie."
PropDescText[4]="Nombre maximum de joueurs dans chaque équipe."
PropDescText[5]="La partie s'arrête après la durée indiquée (en minutes)."
PropDescText[6]="Permettre de choisir la vue de derrière le joueur."
PropDescText[7]="N'autoriser que la vue subjective en mode Spectateur."
PropDescText[8]=N'autoriser que la vue à la troisième personne en mode Spectateur."
PropDescText[9]="Autoriser l'utilisation des points de vue de la carte en mode Spectateur."
PropDescText[10]="Permettre aux joueurs en mode Spectateur de survoler librement la carte."
PropDescText[11]="Permettre aux joueurs morts en attente de réapparition de survoler librement la carte."
PropDescText[12]="Indiquer si les administrateurs peuvent mettre en pause."
PropDescText[13]="Des bots seront ajoutés si nécessaire afin que le match compte au moins ce nombre de participants."
PropDescText[14]="Indiquer le mode de détermination du nombre de bots du match."
PropDescText[15]="Durée d'attente en fin de match avant le passage à la carte suivante."
PropDescText[16]="Adapter automatiquement le niveau de compétence des bots au niveau des joueurs humains."
PropDescText[17]="Nombre de manches à remporter pour gagner la partie."
PropDescText[18]="Nombre maximum de manches pour cette partie."
PropDescText[19]="Délai avant lancement pour permettre la jonction des autres joueurs."
PropDescText[20]="Délai avant lancement pour permettre la jonction des autres joueurs."
PropDescText[21]="Nombre de joueurs devant rejoindre pour permettre le lancement de la partie sur le net."
PropDescText[22]="Obliger les joueurs à choisir une équipe et une arme avant le début de la partie."
PropDescText[23]="Quantité de dégâts que peuvent s'infliger les joueurs d'une même équipe."
PropDescText[24]="Augmenter ou baisser les pénalités de tir allié en cas de dégâts d'artillerie."
PropDescText[25]="Augmenter ou baisser les pénalités de tir allié en cas de dégâts d'explosifs (grenades/charges explosives)."
PropDescText[26]="Des bots rejoindront ou changeront d'équipe pour assurer l'équilibre."
PropDescText[27]="Les joueurs rejoindront automatiquement la plus petite équipe."
PropDescText[28]="Indiquer si les joueurs d'équipes adverses peuvent rejoindre la même salle de discussion privée."
PropDescText[29]="Indiquer la durée à attendre avant d'éjecter un joueur traînard du serveur."
PropDescText[30]="Détermine la pénalité de tir ami."
PropDescText[31]="Détermine l'affichage des messages."
PropDescText[32]="Ecran noir lorsque le joueur est mort et en spectateur."
PropDescText[33]="Ecran noir uniquement quand le joueur est mort et en spectateur sans regarder un joueur."

PropsExtras[0]="0.000000;Inexpérimenté;1.000000;Nouvelle recrue;2.000000;Bleu;3.000000;Soldat du front;4.000000;Soldat expérimenté;5.000000;Vétéran;6.000000;Héros de guerre;7.000000;Fanatique"
PropsExtras[1]="FFP_None;Pas de pénalité;FFP_Kick;Ejection;FFP_SessionBan;Bannissement session;FFP_GlobalBan;Bannissement permanent"
PropsExtras[2]="DM_None;Aucun;DM_OnDeath;Morts personnelles;DM_Personal;Morts/tués personnels;DM_All;Tout"
GameName="Red Orchestra"
Description="Deux équipes se disputent le champ de bataille. L'équipe ayant le plus de frags gagne."

[ROTeamSayDeadMessage]
MessagePrefix="(MORT) *SECTION* "

[ROTeamSayMessage]
MessagePrefix="*SECTION* "

[ROTreadCraft]
VehiclePositionString="dans un Tank"
VehicleNameString="Tank"

[ROVehicle]
TouchMessage="Monter à bord : "

[ROVehicleMessage]
NotQualified="Non qualifié pour contrôler ce véhicule"
VehicleIsEnemy="Impossible d'utiliser un véhicule ennemi"
CannotEnter="Impossible de monter à bord de ce véhicule"

[ROVehicleWaitingMsg]
WaitingForCrew="En attente de membres d'équipage supplémentaires"

[ROVehicleWeaponPawn]
DriverHudName="Conducteur"

[ROVoicePack]
SupportString[0]="Nous avons besoin d'aide !"
SupportString[1]="Aide requise au point :"
SupportString[2]="J'ai besoin de munitions !"
SupportString[3]="Demande soutien de sniper !"
SupportString[4]="Demande soutien de mitrailleuse !"
SupportString[5]="Demande soutien de PTRD !"
SupportString[6]="Faites sauter ce truc !"
SupportString[7]="On a besoin d'un tank !"
SupportString[8]="Appelez l'artillerie !"
SupportString[9]="J'ai besoin d'être emmené !"
SupportAbbrev[0]="Assistance requise"
SupportAbbrev[1]="Assistance requise au point :"
SupportAbbrev[2]="Munitions requises"
SupportAbbrev[3]="Sniper requis"
SupportAbbrev[4]="Soutien de mitrailleuse requis"
SupportAbbrev[5]="Soutien de PTDR requis"
SupportAbbrev[6]="Démolition requise"
SupportAbbrev[7]="Tank requis"
SupportAbbrev[8]="Artillerie requise"
SupportAbbrev[9]="Transport requis"
SupportStringAxis[5]="Il nous faut un Panzerfaust !"
SupportAbbrevAxis[5]="Panzerfaust requis"
EnemyString[0]="Infanterie repérée !"
EnemyString[1]="Mitrailleuse localisée !"
EnemyString[2]="Sniper !"
EnemyString[3]="Sapeur !"
EnemyString[4]="Soldats anti-chars !"
EnemyString[5]="Véhicule léger !"
EnemyString[6]="Attention au tank !"
EnemyString[7]="Tank ennemi repéré !"
EnemyString[8]="Tirs d'artillerie !"
EnemyAbbrev[0]="Infanterie localisée"
EnemyAbbrev[1]="Position de mitrailleuse"
EnemyAbbrev[2]="Sniper"
EnemyAbbrev[3]="Sapeur"
EnemyAbbrev[4]="Soldats anti-chars"
EnemyAbbrev[5]="Véhicule léger"
EnemyAbbrev[6]="Tank"
EnemyAbbrev[7]="Blindé repéré"
EnemyAbbrev[8]="Artillerie"
EnemyStringAxis[3]="Sapeur !"
EnemyStringAxis[6]="Attention, char ennemi repéré !"
EnemyAbbrevAxis[3]="Sapeur"
EnemyAbbrevAxis[6]="Panzer"
AlertString[0]="Grenade !"
AlertString[1]="Go go go !"
AlertString[2]="A couvert !"
AlertString[3]="Halte !"
AlertString[4]="Suivez-moi !"
AlertString[5]="Charge explosive en place !"
AlertString[6]="Tir de couverture !"
AlertString[7]="Tir allié !"
AlertString[8]="Nous sommes attaqués au point"
AlertString[9]="Repli !"
AlertAbbrev[0]="Grenade"
AlertAbbrev[1]="Go go go"
AlertAbbrev[2]="A couvert"
AlertAbbrev[3]="Halte"
AlertAbbrev[4]="Suivez-moi"
AlertAbbrev[5]="Charge explosive en place"
AlertAbbrev[6]="Tir de couverture"
AlertAbbrev[7]="Tir allié"
AlertAbbrev[8]="On nous attaque au point"
AlertAbbrev[9]="Repli"
VehicleDirectionString[0]="Aller à"
VehicleDirectionString[1]="En avant"
VehicleDirectionString[2]="Halte"
VehicleDirectionString[3]="En arrière"
VehicleDirectionString[4]="Aller à gauche"
VehicleDirectionString[5]="Aller à droite"
VehicleDirectionString[6]="5 mètres en avant !"
VehicleDirectionString[7]="5 mètres en arrière !"
VehicleDirectionString[8]="Tourner légèrement à gauche !"
VehicleDirectionString[9]="Tourner légèrement à droite !"
VehicleDirectionAbbrev[0]="Aller à"
VehicleDirectionAbbrev[1]="En avant"
VehicleDirectionAbbrev[2]="Halte"
VehicleDirectionAbbrev[3]="En arrière"
VehicleDirectionAbbrev[4]="Aller à gauche"
VehicleDirectionAbbrev[5]="Aller à droite"
VehicleDirectionAbbrev[6]="5 mètres en avant"
VehicleDirectionAbbrev[7]="5 mètres en arrière"
VehicleDirectionAbbrev[8]="Tourner légèrement à gauche"
VehicleDirectionAbbrev[9]="Tourner légèrement à droite"
VehicleAlertString[0]="Ennemi droit devant !"
VehicleAlertString[1]="Ennemi sur flanc gauche !"
VehicleAlertString[2]="Ennemi sur flanc droit !"
VehicleAlertString[3]="Ennemi derrière !"
VehicleAlertString[4]="Infanterie ennemie à proximité !"
VehicleAlertString[5]="A vos ordres !"
VehicleAlertString[6]="Non, non !"
VehicleAlertString[7]="Au feu !"
VehicleAlertString[8]="Sortez !"
VehicleAlertString[9]="Chargé."
VehicleAlertAbbrev[0]="Ennemi droit devant"
VehicleAlertAbbrev[1]="Ennemi sur flanc gauche"
VehicleAlertAbbrev[2]="Ennemi sur flanc droit"
VehicleAlertAbbrev[3]="Ennemi derrière"
VehicleAlertAbbrev[4]="Infanterie ennemie à proximité"
VehicleAlertAbbrev[5]="Confirmé"
VehicleAlertAbbrev[6]="Négatif"
VehicleAlertAbbrev[7]="Au feu"
VehicleAlertAbbrev[8]="Sortez"
VehicleAlertAbbrev[9]="Chargé"
ExtraString[0]="Je vais te faire la peau !"
ExtraString[1]="On ne se replie pas !"
ExtraString[2]="*insulte*"
ExtraAbbrev[0]="Je vais te faire la peau"
ExtraAbbrev[1]="On ne se replie pas"
ExtraAbbrev[2]="*insulte*"
AckString[0]="A vos ordres !"
AckString[1]="Non, non !"
AckString[2]="Merci"
AckString[3]="Désolé"
AckAbbrev[0]="A vos ordres"
AckAbbrev[1]="Négatif"
AckAbbrev[2]="Merci"
AckAbbrev[3]="Désolé"
OrderString[0]="Attaquez"
OrderString[1]="Défendez"
OrderString[2]="Tenez cette position !"
OrderString[3]="Suivez-moi !"
OrderString[4]="A l'attaque !"
OrderString[5]="Repli !"
OrderString[6]="Feu à volonté !"
OrderString[7]="Cessez le feu !"
OrderAbbrev[0]="Attaquez..."
OrderAbbrev[1]="Défendez..."
OrderAbbrev[2]="Tenez la position"
OrderAbbrev[3]="Suivez-moi"
OrderAbbrev[4]="On bouge"
OrderAbbrev[5]="Repli"
OrderAbbrev[6]="Feu"
OrderAbbrev[7]="Cessez le feu"

[ROWeaponAttachment]
MenuDescription="Description indisponible."

[ROWeaponLostMessage]
WeaponLostMessage="Votre arme vous a sauté des mains !"

